apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: web-analyzer-dev

namePrefix: dev-

resources:
- ../../base

patches:
- patch: |
    - op: replace
      path: /spec/replicas
      value: 1
  target:
    kind: Deployment
    name: web-analyzer
- patch: |
    - op: replace
      path: /metadata/name
      value: web-analyzer-dev
  target:
    kind: Namespace

images:
- name: web-analyzer
  newTag: dev


configMapGenerator:
- behavior: merge
  literals:
  - GIN_MODE=debug
  name: web-analyzer-config

labels:
- includeSelectors: true
  pairs:
    environment: development
