apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: web-analyzer

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - configmap.yaml

commonLabels:
  app: web-analyzer
  managed-by: kustomize